-- ============================================================
-- V1 – Initial schema
-- Compatible with H2 (local dev) and PostgreSQL (production).
-- ============================================================

CREATE TABLE customer_case (
    id            BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    case_ref      VARCHAR(20)   NOT NULL,
    customer_id   VARCHAR(20)   NOT NULL,
    customer_name VARCHAR(120)  NOT NULL,
    case_type     VARCHAR(30)   NOT NULL,
    status        VARCHAR(20)   NOT NULL,
    risk_level    VARCHAR(10)   NOT NULL,
    amount        DECIMAL(18,2),
    description   TEXT          NOT NULL,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_customer_case PRIMARY KEY (id),
    CONSTRAINT uq_case_ref      UNIQUE (case_ref)
);

CREATE TABLE audit_log (
    id            BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    case_id       BIGINT,
    actor         VARCHAR(60)   NOT NULL,
    action        VARCHAR(50)   NOT NULL,
    detail        TEXT,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_audit_log PRIMARY KEY (id)
);

-- ============================================================
-- Seed data
-- ============================================================
INSERT INTO customer_case (case_ref, customer_id, customer_name, case_type, status, risk_level, amount, description) VALUES
('CASE-2026-0001', 'CUST-44821', 'Matti Virtanen',  'FRAUD_ALERT',  'PENDING',      'HIGH',     4200.00,  'Multiple consecutive card-not-present transactions from three different countries within 40 minutes. Velocity threshold exceeded.'),
('CASE-2026-0002', 'CUST-39104', 'Liisa Korhonen',  'KYC_REVIEW',   'PENDING',      'MEDIUM',   NULL,     'Identity document expiry approaching. PEP screening returned one partial name match requiring manual confirmation.'),
('CASE-2026-0003', 'CUST-58720', 'Erik Johansson',  'CREDIT_LIMIT', 'PENDING',      'LOW',      15000.00, 'Customer requests credit limit increase from €15,000 to €30,000. Income verification documents uploaded. No adverse credit history.'),
('CASE-2026-0004', 'CUST-71293', 'Anna Müller',     'AML_FLAG',     'UNDER_REVIEW', 'CRITICAL', 87500.00, 'Structured deposits across six business days totalling €87,500 – pattern consistent with smurfing. STR filed automatically.'),
('CASE-2026-0005', 'CUST-20045', 'Juha Leinonen',   'FRAUD_ALERT',  'PENDING',      'HIGH',     1350.00,  'Chargeback dispute on three transactions. Merchant claims goods delivered; customer denies receipt. Device fingerprint mismatch.'),
('CASE-2026-0006', 'CUST-83471', 'Maria García',    'KYC_REVIEW',   'PENDING',      'MEDIUM',   NULL,     'New business account application. UBO declaration lists three beneficial owners. One owner nationality flagged by sanctions screening.'),
('CASE-2026-0007', 'CUST-62910', 'Pekka Mäkinen',  'CREDIT_LIMIT', 'APPROVED',     'LOW',      5000.00,  'Standard credit limit review, within automated approval parameters. No manual intervention required.'),
('CASE-2026-0008', 'CUST-91234', 'Sophie Dubois',   'AML_FLAG',     'PENDING',      'HIGH',     32000.00, 'Incoming wire from jurisdiction classified as high-risk by FATF. Customer relationship is 7 months old. Purpose of funds unclear.');